//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManualMovementsManager.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceApp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceApp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManualMovementsManager.Domain.Resources.ResourceApp", typeof(ResourceApp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client not found..
        /// </summary>
        public static string CUSTOMER_NOT_FOUND {
            get {
                return ResourceManager.GetString("CUSTOMER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document already exists..
        /// </summary>
        public static string DOCUMENT_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("DOCUMENT_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists.
        /// </summary>
        public static string EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        public static string INVALID_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must not exceed 100 characters.
        /// </summary>
        public static string MAX_LENGTH_EMAIL {
            get {
                return ResourceManager.GetString("MAX_LENGTH_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be at least 3 characters long..
        /// </summary>
        public static string MIN_LENGTH_NAME {
            get {
                return ResourceManager.GetString("MIN_LENGTH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long.
        /// </summary>
        public static string MIN_LENGTH_PASSWORD {
            get {
                return ResourceManager.GetString("MIN_LENGTH_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is mandatory..
        /// </summary>
        public static string REQUIRED_CITY {
            get {
                return ResourceManager.GetString("REQUIRED_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required..
        /// </summary>
        public static string REQUIRED_COUNTRY {
            get {
                return ResourceManager.GetString("REQUIRED_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Email.
        /// </summary>
        public static string REQUIRED_EMAIL {
            get {
                return ResourceManager.GetString("REQUIRED_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string REQUIRED_NAME {
            get {
                return ResourceManager.GetString("REQUIRED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighborhood is mandatory..
        /// </summary>
        public static string REQUIRED_NEIGHBORHOOD {
            get {
                return ResourceManager.GetString("REQUIRED_NEIGHBORHOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required!.
        /// </summary>
        public static string REQUIRED_PASSWORD {
            get {
                return ResourceManager.GetString("REQUIRED_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone is required!.
        /// </summary>
        public static string REQUIRED_PHONE {
            get {
                return ResourceManager.GetString("REQUIRED_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is mandatory..
        /// </summary>
        public static string REQUIRED_STATE {
            get {
                return ResourceManager.GetString("REQUIRED_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street is mandatory..
        /// </summary>
        public static string REQUIRED_STREET {
            get {
                return ResourceManager.GetString("REQUIRED_STREET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP code is required..
        /// </summary>
        public static string REQUIRED_ZIPCODE {
            get {
                return ResourceManager.GetString("REQUIRED_ZIPCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test version word.
        /// </summary>
        public static string VERSION_TEST_WORD {
            get {
                return ResourceManager.GetString("VERSION_TEST_WORD", resourceCulture);
            }
        }
    }
}
